### ISSUE TITLE
[Other] Определить основную сюжетную линию

### ISSUE THREAD

**Issue by tvklo** [tvklo/DarknessOfPaladins#10]
Написать краткое содержание сюжета игры

**Comment by tvklo** [comment]
Предлагаю сделать гг шизофреиком и чтобы ему везде мерещились провокации. Например чтобы было много диалогов вида "На Вас косо смотрит продавец на рынке" -> "Подойти и грубо залупнуться" -> "Вы мерты..." и много где сделать такие подьебки чтобы игрок сам догадался что с его персонаж изначально ебанутый.

**Comment by OK1E** [comment]
Чтото леша тоже все время про шизофреничного гг грезил на лесенке месяц назад. ядерный титбит какой то текстовый получиться.

**Comment by PaladinOfFate** [comment]
а вот тут заминочка получается, предлагаю сначала обозначить классы персонажей. По сюжету выбрав например мага, ему будет не интересно шастать по воинским казармам и наоборот. Можно так же сделать разветвления для разных классов, но что бы потом они сходились в одну точку старта основной линии. И уже из этой точки можно начинать лепить основу сюжета.
=======================
Есть интересный приём сценаристов: Начинать сценарий с конца! Если конец будет например: убить дракона из вулкана "Плю-плю", то потом легче будет подводить сюжет к этому самому вулкану и дракону, постепенно уходя к началу сюжета.

**Comment by OK1E** [comment]
Для начала предлагаю определиться с самойй игрой
а) сеттинг
б) боевка. прикручитваь боевку ДнД? или делать свою какуюто боевку?(кстати боевка будет пошаговая же?)
с) геймплей я так понял тоже аля пошаговый (пойти вправо / пойти влево?) (как навелка с определенными роутами?)

**Comment by PaladinOfFate** [comment]
Да кстати! Предлагаю вообще опустить тему мечей и магии и придумать что-то другое? Космос? Будущее? Жизнь под водой? Выживание в пустыне?

**Comment by OK1E** [comment]
отвечать удобнее по пунктно, большими кирпичиками текста. кстати что то в духе мини игр из коссмических рейнджкеров РИЛ интересно? кто играл отметтесь. там про разнообразные планеты и всякие задачки головоломочки инклюд

**Comment by OK1E** [comment]
космическая квест рпг, в сюжете персонаж шастает по 3 планетам. у каждого девелопера по планете. очередность выбирается в конце
